project:
  type: website

  output-dir: _site

website:
  title: "DF's Blog"
  description: "Blog pessoal"

  site-url: https://blog.dftv.spikeystudio.com/

  open-graph: true
  cookie-consent: false

  favicon: assets/icons/favicon.ico

  search:
    location: navbar
    type: overlay
    keyboard-shortcut: ["?", "H"]

  navbar:
    search: true

    left: 
      - text: "Posts"
        href: posts/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Articles"
        href: articles/index.qmd
      - text: "Achievements"
        href: achievements/index.qmd
      - text: "About me"
        menu:
        - icon: file-person-fill
          text: "Resume"
          href: aboutMe/resume.qmd

    tools:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/df-danielfilho/
        target: _blank
      - icon: github
        href: https://github.com/dftv
        target: _blank
      - icon: rss
        href: index.xml
        target: _blank

  page-footer: 
    center: "Copyright © 2025 - Spikey Studio"

format:
  html:
    theme:
      light: themes/light_theme.scss
      dark: themes/dark_theme.scss

    date-format: long

    page-layout: full
    
    toc: false

  pdf: default

resources:
  - CNAME

execute: 
  freeze: auto

