---
title: "Step by step guide on how to ruin your company and your team with AI"
subtitle: "A roadmap to the quickest way to lose your team's trust"
description: "This post aims to apply psychology concepts to address a sensitive topic for those who are limited by the use of generative artificial intelligence tools in the professional environment, acting as a direct attack on the intellect, raising questions and seeking plausible solutions."

date: "02/12/2025"

categories:
  - Behavioral Analysis
  - Artificial Intelligence
  - Ethics
  - Management

bibliography: bibliography.bib

draft: false
---

It's pretty easy to keep a team organized with a well-defined workflow, right?

But if you want to showcase your incompetence or simply watch everything go up in flames, this post is for you!

Already in a leadership position and ready to swim against the tide? Here are some tips to quickly turn everything upside down, bringing chaos and demotivation as fast as possible to everyone relying on your work.

And the best part:

* Without much effort;
* Reducing your workload;
* And with the most groundbreaking tool of the moment[^1]!

To better understand where you can fail and make it blatantly obvious to everyone, let’s break down the following workflow I’ve created:

```{mermaid}
%%| fig-align: center
flowchart TB;
  T1[
    By #quot;optimizing#quot; with AI processes like:
  ]

  subgraph G1[ ]
    G1.1[
      Sending corporate messages
      or emails
    ]

    G1.2[
      Problem-solving
    ]

    G1.3[Task delegation]

    G1.4[Decision-making]
  end

  subgraph G2[ ]
    subgraph G2.1[ ]
      direction TB

      G2.1.1[Lack of empathy and social skills]
      G2.1.2[Lack of contextual awareness]
      G2.1.3[Ignoring feedback]
      G2.1.4[Ineffective communication]

      G2.1.1 --> G2.1.2
      G2.1.2 --> G2.1.3
      G2.1.3 --> G2.1.4
    end

    subgraph G2.2[ ]
      direction TB

      G2.2.1[Technical superficiality]
      G2.2.2[Lack of active leadership]
      G2.2.3[Impersonal decisions with no relevant contextual basis]
      G2.2.4[Inability to solve problems]

      G2.2.1 --> G2.2.2
      G2.2.2 --> G2.2.3
      G2.2.3 --> G2.2.4
    end

    subgraph G2.3[ ]
      direction TB

      G2.3.1[Technical superficiality]
      G2.3.2[Lack of understanding of internal processes and business rules]
      G2.3.3[Neglect of organization and planning]
      G2.3.4[Inefficiency in delegating tasks]

      G2.3.1 --> G2.3.2
      G2.3.2 --> G2.3.3
      G2.3.3 --> G2.3.4
    end

    subgraph G2.4[ ]
      direction TB

      G2.4.1[Lack of active leadership]
      G2.4.2[Ignoring feedback and human factors]
      G2.4.3[Neglect of organization and planning]
      G2.4.4[Inability to make assertive decisions]

      G2.4.1 --> G2.4.2
      G2.4.2 --> G2.4.3
      G2.4.3 --> G2.4.4
    end
  end

  subgraph G3[ ]
    G3.1[Loss of trust in leadership]
    G3.2[Doubt about your expertise]
    G3.3[Increase in mistakes and rework]
    G3.4[Internal conflicts between teams and departments]
  end

  T2[Demotivated and unproductive work environment]

  T1 -->  G1.1 & G1.2 & G1.3 & G1.4

  G1.1 -- You demonstrate --> G2.1
  G1.2 -- You demonstrate --> G2.2
  G1.3 -- You demonstrate --> G2.3
  G1.4 -- You demonstrate --> G2.4

  G2.1 -- Leading to --> G3.1
  G2.2 -- Leading to --> G3.2
  G2.3 -- Leading to --> G3.3
  G2.4 -- Leading to --> G3.4

  G3.1 & G3.2 & G3.3 & G3.4 -- Resulting in --> T2
```

See how easy it is to visualize how simple processes can trigger a chain of problems that will inevitably lead to your undeniable exclusion and eventual termination?

---

Maybe you felt personally attacked by how this topic was introduced.

If so, part of that is due to the Psychological Reactance phenomenon[^2] combined with elements of Reverse Psychology[^3].

By deliberately exaggerating the impact of the indiscriminate use of this miraculous tool[^1] — framing as "correct" something that is generally frowned upon—you, as the likely target audience, are naturally inclined to resist and deny it. After all, how hard is it to admit that what currently makes you a professional could easily be the nightmare of many of your colleagues? Or worse, that you could be replaced by an inanimate tool?

This negative reaction from this category of workers is expected since they are already dependent on this enabler[^1], and the idea that it might be harmful—not just to them but to everyone around them—doesn’t fit the short-term results they have experienced so far.

From a broader perspective, part of the blame may not be entirely yours but rather the fault of those who sold you the idea that this tool[^1] is the solution to all your monotonous tasks. However, the lack of supervision and limitation of its use will always lead to its application in a wide range of areas—without proper impact assessment and consideration of consequences—far beyond the monotonous tasks it was originally designed for[^1].

Currently, most AI models are in constant development and far from their peak, with limitations and flaws that are imperceptible at first glance. This is because their entire functioning is designed to socially please the user, meaning they are structured in a way that prevents you from feeling like you're facing incorrect or nonsensical information.

Not convinced? Maybe you’re still caught in Automation Bias[^4].
To open your eyes, here are some phenomena that might be happening to you daily without you even realizing it:

* **Hallucinations**[^5], where the tool[^1] generates responses that, while appearing coherent, have no real basis, being merely a statistical approximation[^8] of what would best fit the given context.
This happens due to the lack of logical reasoning in these products[^7], making some responses essentially just "educated guesses."
* **Context Window**[^6], which limits the amount of information the tool[^1] can process at once, meaning that it often fails to grasp the full context of a situation, leading to responses that don’t align with reality. This becomes even more concerning as there is no explicit indication of what is or isn’t discarded by the tool[^1].

In conclusion, the use of AI tools in corporate environments should be approached with caution and always under the supervision of a qualified professional. After all, no tool can replace critical thinking and assertive decision-making—no matter how convincing or convenient it may seem.

I hope this reading has helped you open your eyes to the dangers of so-called "miracle" automation tools, both for current AI and for future technologies that may emerge.

::: {.callout-tip}
## Remember

The problem is never the tool itself, but how it is used!
:::

---

[^1]: Generative Artificial Intelligence
[^2]: See more at @UnderstandingPsychologicalReactance
[^3]: See more at @HowDoesReversePsychologyWork
[^4]: See more at @DoesAutomationBiasDecisionMaking
[^5]: See more at @WhatAreAIHallucinations
[^6]: See more at @WhatIsAContextWindow
[^7]: Generative artificial intelligences
[^8]: Which may result in an incorrect weight distribution

:::{.column-body}
<script src="https://giscus.app/client.js"
        data-repo="dftv/blog_quarto"
        data-repo-id="R_kgDONv_J5g"
        data-category="Posts"
        data-mapping="number"
        data-term="8"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
:::
