---
title: Daniel R. T. Filho
description: Research & Development Engineer

jupyter: python3
---

> Senior Full-Stack Engineer,  
> Data Scientist and Machine Learning Enthusiast

::: {.grid .d-block .d-md-grid}

::: {.g-col-12 .g-col-md-8}

### Overview

I am a Full-Stack Developer with extensive
experience in a variety of technologies. My ability to
integrate Front-End and Back-End allows me to
create comprehensive and efficient solutions. With
a quick learning ability and flexibility in workflow, I
adapt rapidly to new technologies and project
demands, ensuring the delivery of high-quality
products.

---

### Experience
```{python}
# | echo: false
from widgets import EmploymentType, ExperienceSchema, LocationType, PositionSchema, experienceWidget
from datetime import date
```


```{python}
# | echo: false
experienceWidget(
    ExperienceSchema(
        company="Argus Solutions",
        positions=[
            PositionSchema(
                title="Senior Full-Stack Developer and Data Scientist",
                startDate=date(2025, 1, 1),
                present=True,
                location="Piracicaba, São Paulo, Brazil",
                employmentType=EmploymentType.FULL_TIME,
                locationType=LocationType.HYBRID,
            ),
            PositionSchema(
                title="Senior Full-Stack Developer",
                startDate=date(2024, 7, 1),
                endDate=date(2025, 1, 1),
                location="Piracicaba, São Paulo, Brazil",
                employmentType=EmploymentType.FULL_TIME,
                locationType=LocationType.HYBRID,
            ),
        ],
    ),
)
```

```{python}
# | echo: false
experienceWidget(
    ExperienceSchema(
        company="Guild Market",
        positions=[
            PositionSchema(
                title="Pleno Full-stack Developer",
                startDate=date(2024, 6, 1),
                endDate=date(2024, 7, 1),
                location="Macaé, Rio de Janeiro, Brazil",
                employmentType=EmploymentType.FREELANCE,
                locationType=LocationType.REMOTE,
            ),
        ],
    ),
)
```

```{python}
# | echo: false
experienceWidget(
    ExperienceSchema(
        company="Woodyverso",
        positions=[
            PositionSchema(
                title="Pleno Mobile Developer and Junior 3D Modeler",
                startDate=date(2022, 10, 1),
                endDate=date(2023, 2, 1),
                location="Macaé, Rio de Janeiro, Brazil",
                employmentType=EmploymentType.FREELANCE,
                locationType=LocationType.REMOTE,
            ),
        ],
    ),
)
```

```{python}
# | echo: false
experienceWidget(
    ExperienceSchema(
        company="EMARTIM",
        positions=[
            PositionSchema(
                title="Junior Full-stack and Mobile Developer",
                startDate=date(2022, 12, 1),
                endDate=date(2024, 3, 1),
                location="Piracicaba, São Paulo, Brazil",
                employmentType=EmploymentType.FULL_TIME,
                locationType=LocationType.REMOTE,
            ),
            PositionSchema(
                title="Junior Mobile Developer",
                startDate=date(2022, 6, 1),
                endDate=date(2022, 12, 1),
                location="Piracicaba, São Paulo, Brazil",
                employmentType=EmploymentType.FULL_TIME,
                locationType=LocationType.REMOTE,
            ),
        ],
    ),
)
```

```{python}
# | echo: false
experienceWidget(
    ExperienceSchema(
        company="GBM Tech & Control",
        positions=[
            PositionSchema(
                title="Intern Front-End Developer",
                startDate=date(2022, 2, 1),
                endDate=date(2022, 5, 1),
                location="Santos, São Paulo, Brazil",
                employmentType=EmploymentType.INTERNSHIP,
                locationType=LocationType.HYBRID,
            ),
        ],
    ),
)
```

:::

::: {.g-col-12  .g-col-md-4}

::: {.d-block .d-md-none}

---

:::

### Education

```{python}
# | echo: false
from widgets import educationWidget, EducationSchema
from datetime import date
```

```{python}
# | echo: false
educationWidget(
    EducationSchema(
        degree="Bachelor of Engineering in Mechatronics",
        institution="Unicesumar",
        startDate=date(2024, 5, 1),
        present=True,
    )
)
```

```{python}
# | echo: false
educationWidget(
    EducationSchema(
        degree="Associate Degree in Internet Systems",
        institution="Unicesumar",
        startDate=date(2022, 7, 1),
        endDate=date(2024, 7, 1),
    )
)
```

```{python}
# | echo: false
educationWidget(
    EducationSchema(
        degree="Technical Degree in Systems Development",
        institution="Peruíbe State Technical School (ETEC)",
        startDate=date(2019, 1, 1),
        endDate=date(2021, 12, 1),
    )
)
```

##### And more: [Licenses and certificates](https://www.linkedin.com/in/df-danielfilho/details/certifications/){target="_blank"}

##### See also my [Skills](https://www.linkedin.com/in/df-danielfilho/details/skills/){target="_blank"}

---

### Main Languages

::: {.grid}

::: {.column}
- Python
- Julia
- R
- Dart
- C#
- PHP
- SQL
:::

::: {.column}
- NoSQL
- Kotlin
- Java
- JavaScript
- TypeScript
- HTML
- CSS
:::

:::

---

### Some Frameworks and Technologies

::: {.grid}

::: {.column}
- Flutter
- React
- React Native
- Express.js
- CodeIgniter
- FastAPI
- ASP.NET
:::

::: {.column}
- MySQL
- MariaDB
- MongoDB
- Node.js
- Shiny
- Oxygen.jl
- Jupyter
:::

:::

:::

:::