name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: echo "QUARTO_CHROMIUM_HEADLESS_MODE=1" >> $GITHUB_ENV

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libgbm1 \
            google-chrome-stable

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Quarto Dependencies
        run: quarto install tinytex --no-prompt

      - name: Cache TinyTeX
        uses: actions/cache@v3
        with:
          path: ~/.TinyTeX
          key: ${{ runner.os }}-tinytex

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - name: Setup local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Cache Poetry virtual environment
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install Python dependencies with Poetry
        run: poetry install

      - name: Ensure Poetry virtual environment is used
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Render site HTML
        run: quarto render --to html --log-level debug

      - name: Render PDF pages (optional)
        run: quarto render --to pdf --log-level debug --chromium-args="--no-sandbox"

      - name: Publish site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
